### ISSUE TITLE
Add pypy 3.8 and 3.9

### ISSUE THREAD

**Issue by maresb** [conda-forge/aesara-feedstock#96]

**Comment by brandonwillard** [comment]
We should have at least one version of PyPy tested (preferably the "most representative" one), but I don't think we need full coverage (i.e. all versions) right now.

**Comment by maresb** [comment]
Migrating Aesara to the newer versions of PyPy is currently being blocked by the requirement https://github.com/conda-forge/scipy-feedstock/pull/204.

If you want to have a PyPy tested for each version, we could reenable PyPy 3.7 and allow the BLAS warning.

**Comment by brandonwillard** [comment]
> If you want to have a PyPy tested for each version, we could reenable PyPy 3.7 and allow the BLAS warning.

We can wait until https://github.com/conda-forge/scipy-feedstock/pull/204 goes through.
